version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: daily
    labels: 
     - "🤖 Dependencies"