name: "🤔 Question"
title: "\U0001F917 [Question]: "
description: Ask a question so we can help you easily.
labels: ["🤔 Question"]

body:
  - type: textarea
    id: description
    attributes:
      label: "Question Description"
      description: "A clear and detailed description of the question."
      placeholder: "Explain your question clearly, and in detail."
    validations:
      required: true