name: build
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Linting
      run: make lint

    - name: Quality Checks
      run: make quality
    
    - name: Tests with coverage
      run: make coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.6.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
